version: '3.8'

services:
  gtasks-notion-sync:
    build: 
      context: .
      dockerfile: Dockerfile
      # Force rebuild on every docker-compose up
      no_cache: true
    image: gtasks-notion-integration:latest
    container_name: gtasks-notion-sync
    restart: unless-stopped
    
    # Always pull the latest version and rebuild
    pull_policy: build
    
    # Environment variables (you can override these)
    environment:
      - TZ=Asia/Kolkata
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=1
      
    # Mount volumes for persistence and configuration
    volumes:
      # Persist logs
      - ./logs:/app/logs
      # Persist category mappings and any data files
      - ./data:/app/data
      # Mount configuration file (required)
      - ./config.yaml:/app/config.yaml:ro
      # Mount Google credentials (required)
      - ./client_secret.json:/app/client_secret.json:ro
      # Mount or create token file for Google auth persistence
      - ./token.pkl:/app/token.pkl
    
    # Resource limits for optimization
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 1m
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    # Network configuration (optional)
    networks:
      - gtasks-network

# Optional: Create a custom network
networks:
  gtasks-network:
    driver: bridge

# Optional: Named volumes for better management
volumes:
  logs:
    driver: local
  data:
    driver: local